/**
 * Список названий ручек в том порядке, как в таблице (Тип / Название / Цвет).
 * Порядок соответствует описанию изображения: сначала простые цвета, затем матовые/сатин/хром, комбинации, затем без явного цвета.
 */
export const HANDLE_NAMES_ORDERED: string[] = [
  'MIRA_ЧЕРНЫЙ',
  'MIRA_БЕЛЫЙ',
  'MIRA_ГРАФИТ',
  'SULLA_белая',
  'SULLA_черная',
  'LOT_ЧЕРНЫЙ',
  'LOT_ГРАФИТ',
  'YSTAD_черн',
  'YSTAD_белый',
  'KAFFEE_БЕЛЫЙ',
  'KAFFEE_ЧЕРНЫЙ',
  'PLATEAU_черн',
  'PLATEAU_белый',
  'ОАКА-ЧЕРНЫЙ',
  'GARAK-ЧЕРНЫЙ',
  'CAYAN_черный',
  'AZRIELI_Черн',
  'AZRIELI_Золото',
  'FUKOKU_черный',
  'PISA_черн',
  'AKCENT_черн',
  'FLOU_черный',
  'MERIDIAN_черный',
  'СОМЕТА R5-Черн',
  'СОМЕТА R5-Бел',
  'HORIZONT S5-БЕЛЫЙ',
  'HORIZONT S5-ЧЕРНЫЙ',
  'PANATHENAIC R5-БЕЛЫЙ',
  'PANATHENAIC_ЧЕРНЫЙ',
  'ALLURE_шампань',
  'ALLURE_черный',
  'MIRA_ХРОМ-МАТ',
  'MIRA_МАТ. САТИНОВЫЙ НИКЕЛЬ',
  'SULLA_графит браш',
  'PIERRES_ХРОМ-МАТ',
  'LOT_XPOM-MAT',
  'LOT_САТИНОВЫЙ НИКЕЛЬ',
  'LOT_МАТ. САТИНОВОЕ ЗОЛОТО',
  'SOUK_хром-мат',
  'YSTAD_никель',
  'YSTAD_хром',
  'KAFFEE_MAT.ХРОМ',
  'PLATEAU_мат.хром',
  'ОАКА-ХРОМ-МАТ',
  'GARAK-MAT. CATXPOM',
  'GARAK-РАЗНОЕ-МАТ.САТНИКЕЛЬ',
  'CAYAN_ХромМат',
  'CAYAN_матовый никель',
  'AZRIELI_СатинМат',
  'AZRIELI_ХромМат',
  'EON_ХРОМ+МАТ',
  'FLEX_хром/матхром',
  'FUKOKU_тем.НИКЕЛЬ',
  'FUKOKU_SC_ХРОМ',
  'GVI_SC_МАТХРОМ',
  'PANTS-НИКЕЛЬ_МАТ+ЧЕРНЫЙ_НИКЕЛЬ',
  'W_SC_никель хром',
  'COLUMN_мат.никель/хром',
  'COLUMN_мат.золото/золото',
  'COLUMN_белый/черный никель',
  'PISA_никель черн',
  'PISA_никель хром',
  'MOSAIC MH-11-ХРОМ',
  'MOSAIC MH-11-бронза',
  'AKCENT_золото мат',
  'AKCENT_хром мат',
  'FLOU_матовый_белый',
  'FLOU_матовое_золото',
  'FLOU_матовый_хром',
  'MERIDIAN_матовый_хром',
  'MERIDIAN_матовое_золото',
  'COMETA R5-РАЗНОЕ-КОФЕ',
  'COMETA R5-РАЗНОЕ-МАТ.НИКЕЛЬ',
  'COMETA R5-ХРОМ-МАТ',
  'COMETA R5-ХРОМ',
  'HORIZONT S5-РАЗНОЕ-Золото',
  'HORIZONT S5-PАЗНОЕ-НИКЕЛЬ-МАТ',
  'HORIZONT S5-ХРОМ',
  'HORIZONT_Золотомат',
  'HORIZONT_мат_хром',
  'PANATHENAIC R5-РАЗНОЕ-КОФЕ',
  'PANATHENAIC R5-РАЗНОЕ-МАТ. НИКЕЛЬ',
  'PANATHENAIC R5-ХРОМ-МАТ',
  'PANATHENAIC R5-ХРОМ',
  'ALLURE_золото мат',
  'ALLURE_черный графит',
  'ALLURE_матовый хром',
  'EON_ХРОМ+БЕЛЫЙ',
  'EON_ГРАФИТ+ХРОМ',
  'FLEX_ХРОМ+белый',
  'FLEX_ГРАФИТ+ХРОМ',
  'LINE BL',
  'SLIM NM',
  'SKY_G',
  'FLAME_GM',
  'NANO_GM',
  'PROMO BL',
  'ROCKET NM',
  'PRIME_GR',
  'PRIZMA BL',
  'BARREL SG',
  'PRIDE SSC',
  'MAIN SSG',
  'VIVA BL',
  'FORTUNA_SSC',
  'SPUTNIK_GM',
  'FORCE G',
  'NIMB_BL',
  'QUASAR BL',
  'RADIANT BL',
  'STELLAR BL',
  'ECLIPTIC_MS',
  'REFLEX MS',
  'INTRIGUE_MG',
  'QUASAR MG',
  'OPUS MG',
];
